// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package todo

// Injectors from wire.go:

func Setup() (*App, error) {
	dbConnStr := NewDBConnStr()
	dbDriverName := NewDBDriverName()
	controller := NewController()
	router := NewRouter(controller)
	app, err := NewToDoApp(dbConnStr, dbDriverName, router)
	if err != nil {
		return nil, err
	}
	return app, nil
}
